En este notebook se saca un archivo con Unique ID y Fecha ==> "date_id"

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import datetime
sns.set_theme(style='darkgrid')

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

**Requerimiento:** analizar la situacion actual de las ventas de la compañía por:

* Producto -> Productos más vendidos y productos menos populares
* Tienda -> Precios por tienda (y añadir cantidades)
* Ciudad -> Mirar solo las de NY, Boston, Philly.

In [3]:
sales = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD input/item_sales.csv")
calendar = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD input/daily_calendar_with_events.csv")

In [4]:
#Creamos la lista de variables idenfiticadoras y variables de medidas.
lista = sales.columns.values.tolist()
lista_1 = lista[0:7]
del lista[0:7]

In [5]:
#Utilizamos la función MELT
sales = sales.melt(id_vars=lista_1, var_name="date", value_name= "units")

In [6]:
sales.head()

,id,item,category,department,store,store_code,region,date,units
0,ACCESORIES_1_001_NYC_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,d_1,0
1,ACCESORIES_1_002_NYC_1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,d_1,0
2,ACCESORIES_1_003_NYC_1,ACCESORIES_1_003,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,d_1,0
3,ACCESORIES_1_004_NYC_1,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,d_1,0
4,ACCESORIES_1_005_NYC_1,ACCESORIES_1_005,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,d_1,0

In [7]:
sales.shape

(58327370, 9)

In [8]:
calendar["date"] = pd.to_datetime(calendar["date"], format = "%Y-%m-%d")
calendar["week"] = calendar["date"].dt.isocalendar().week.astype(str)
calendar["year"] = calendar["date"].dt.isocalendar().year.astype(str)
calendar["year_week"] = calendar["year"] + "-" + calendar["week"]

In [9]:
sales.rename(columns={"date": "d"}, inplace = True)

In [10]:
sales.shape

(58327370, 9)

In [11]:
sales_calendar = pd.merge(
    left = sales,
    right = calendar,
    how = 'left',
    on = ["d"])

In [12]:
sales_calendar.head()

,id,item,category,department,store,store_code,region,d,units,date,weekday,weekday_int,event,week,year,year_week
0,ACCESORIES_1_001_NYC_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,d_1,0,2011-01-29,Saturday,1,NaN,4,2011,2011-4
1,ACCESORIES_1_002_NYC_1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,d_1,0,2011-01-29,Saturday,1,NaN,4,2011,2011-4
2,ACCESORIES_1_003_NYC_1,ACCESORIES_1_003,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,d_1,0,2011-01-29,Saturday,1,NaN,4,2011,2011-4
3,ACCESORIES_1_004_NYC_1,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,d_1,0,2011-01-29,Saturday,1,NaN,4,2011,2011-4
4,ACCESORIES_1_005_NYC_1,ACCESORIES_1_005,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,d_1,0,2011-01-29,Saturday,1,NaN,4,2011,2011-4

In [13]:
lista = sales_calendar.columns.values.tolist()
lista.remove("id")
lista.remove("date")
lista.remove("year_week")
lista

['item',
 'category',
 'department',
 'store',
 'store_code',
 'region',
 'd',
 'units',
 'weekday',
 'weekday_int',
 'event',
 'week',
 'year']

In [14]:
sales_calendar.drop(lista, axis=1, inplace=True)

In [15]:
sales_calendar.head()

                       id       date year_week
0  ACCESORIES_1_001_NYC_1 2011-01-29    2011-4
1  ACCESORIES_1_002_NYC_1 2011-01-29    2011-4
2  ACCESORIES_1_003_NYC_1 2011-01-29    2011-4
3  ACCESORIES_1_004_NYC_1 2011-01-29    2011-4
4  ACCESORIES_1_005_NYC_1 2011-01-29    2011-4

In [16]:
date_id = sales_calendar.groupby(["year_week", "id"]).first()

In [17]:
date_id.to_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/date_id_2.csv")

In [18]:
date_id

                                        date
year_week id
2011-10   ACCESORIES_1_001_BOS_1  2011-03-07
          ACCESORIES_1_001_BOS_2  2011-03-07
          ACCESORIES_1_001_BOS_3  2011-03-07
          ACCESORIES_1_001_NYC_1  2011-03-07
          ACCESORIES_1_001_NYC_2  2011-03-07
...                                      ...
2016-9    SUPERMARKET_3_827_NYC_3 2016-02-29
          SUPERMARKET_3_827_NYC_4 2016-02-29
          SUPERMARKET_3_827_PHI_1 2016-02-29
          SUPERMARKET_3_827_PHI_2 2016-02-29
          SUPERMARKET_3_827_PHI_3 2016-02-29

[8354260 rows x 1 columns]