En este notebook se unifican todos. Salida Final

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
import pandas as pd

In [10]:
sales_calendar = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/sales_calendar_1.csv")

In [11]:
sales_calendar.head()

  year_week                      id  units
0   2011-10  ACCESORIES_1_001_BOS_1      0
1   2011-10  ACCESORIES_1_001_BOS_2      0
2   2011-10  ACCESORIES_1_001_BOS_3      0
3   2011-10  ACCESORIES_1_001_NYC_1      0
4   2011-10  ACCESORIES_1_001_NYC_2      0

In [12]:
sales = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD input/item_sales.csv")

In [13]:
sales.head()

,id,item,category,department,store,store_code,region,d_1,d_2,d_3,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,ACCESORIES_1_001_NYC_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,ACCESORIES_1_002_NYC_1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,ACCESORIES_1_003_NYC_1,ACCESORIES_1_003,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,ACCESORIES_1_004_NYC_1,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,ACCESORIES_1_005_NYC_1,ACCESORIES_1_005,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [14]:
lista = sales.columns.values.tolist()
lista = lista[7:]
lista
sales.drop(lista, axis=1, inplace=True)

In [15]:
sales.shape

(30490, 7)

In [16]:
sales_calendar.shape

(8354260, 3)

In [17]:
sales_calendar = pd.merge(
    left = sales_calendar,
    right = sales,
    how = "left",
    on = ["id"]
)

In [18]:
sales_calendar.head()

,year_week,id,units,item,category,department,store,store_code,region
0,2011-10,ACCESORIES_1_001_BOS_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston
1,2011-10,ACCESORIES_1_001_BOS_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Roxbury,BOS_2,Boston
2,2011-10,ACCESORIES_1_001_BOS_3,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston
3,2011-10,ACCESORIES_1_001_NYC_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York
4,2011-10,ACCESORIES_1_001_NYC_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York

In [19]:
sales.shape

(30490, 7)

In [20]:
date_id = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/date_id_2.csv")

In [21]:
date_id.head()

  year_week                      id        date
0   2011-10  ACCESORIES_1_001_BOS_1  2011-03-07
1   2011-10  ACCESORIES_1_001_BOS_2  2011-03-07
2   2011-10  ACCESORIES_1_001_BOS_3  2011-03-07
3   2011-10  ACCESORIES_1_001_NYC_1  2011-03-07
4   2011-10  ACCESORIES_1_001_NYC_2  2011-03-07

In [22]:
sales_calendar = pd.merge(
    left = sales_calendar,
    right = date_id,
    how = 'left',
    on = ["id", "year_week"])

In [23]:
sales_calendar.head()

,year_week,id,units,item,category,department,store,store_code,region,date
0,2011-10,ACCESORIES_1_001_BOS_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07
1,2011-10,ACCESORIES_1_001_BOS_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Roxbury,BOS_2,Boston,2011-03-07
2,2011-10,ACCESORIES_1_001_BOS_3,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07
3,2011-10,ACCESORIES_1_001_NYC_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-03-07
4,2011-10,ACCESORIES_1_001_NYC_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07

In [24]:
prices = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD input/item_prices.csv")

In [25]:
prices["yearweek2"] = prices['yearweek'].astype(str)
prices["year"] = prices['yearweek2'].str[:4]
prices["week"] = prices["yearweek2"].str[4:6]
prices["year_week"] = prices["year"] + "-" + prices["week"]

In [26]:
prices.head()

,item,category,store_code,yearweek,sell_price,yearweek2,year,week,year_week
0,ACCESORIES_1_001,ACCESORIES,NYC_1,201328.0,12.7414,201328.0,2013,28,2013-28
1,ACCESORIES_1_001,ACCESORIES,NYC_1,201329.0,12.7414,201329.0,2013,29,2013-29
2,ACCESORIES_1_001,ACCESORIES,NYC_1,201330.0,10.9858,201330.0,2013,30,2013-30
3,ACCESORIES_1_001,ACCESORIES,NYC_1,201331.0,10.9858,201331.0,2013,31,2013-31
4,ACCESORIES_1_001,ACCESORIES,NYC_1,201332.0,10.9858,201332.0,2013,32,2013-32

In [27]:
prices["id"] = prices["item"] + "_" + prices["store_code"]

In [28]:
prices.drop(["yearweek", "yearweek2"], axis=1, inplace=True)

In [29]:
prices.head()

,item,category,store_code,sell_price,year,week,year_week,id
0,ACCESORIES_1_001,ACCESORIES,NYC_1,12.7414,2013,28,2013-28,ACCESORIES_1_001_NYC_1
1,ACCESORIES_1_001,ACCESORIES,NYC_1,12.7414,2013,29,2013-29,ACCESORIES_1_001_NYC_1
2,ACCESORIES_1_001,ACCESORIES,NYC_1,10.9858,2013,30,2013-30,ACCESORIES_1_001_NYC_1
3,ACCESORIES_1_001,ACCESORIES,NYC_1,10.9858,2013,31,2013-31,ACCESORIES_1_001_NYC_1
4,ACCESORIES_1_001,ACCESORIES,NYC_1,10.9858,2013,32,2013-32,ACCESORIES_1_001_NYC_1

In [30]:
prices.drop(["item", "category", "store_code"], axis=1, inplace = True)

In [31]:
sales_calendar_prices = pd.merge(
    left = sales_calendar,
    right = prices,
    how = "left",
    on = ["id", "year_week" ]
)

In [32]:
sales_calendar_prices.drop(["year_week"], axis=1, inplace = True)

In [33]:
sales_calendar_prices.head()

,id,units,item,category,department,store,store_code,region,date,sell_price,year,week
0,ACCESORIES_1_001_BOS_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,NaN,NaN,NaN
1,ACCESORIES_1_001_BOS_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Roxbury,BOS_2,Boston,2011-03-07,NaN,NaN,NaN
2,ACCESORIES_1_001_BOS_3,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07,NaN,NaN,NaN
3,ACCESORIES_1_001_NYC_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-03-07,NaN,NaN,NaN
4,ACCESORIES_1_001_NYC_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07,NaN,NaN,NaN

In [34]:
database = sales_calendar_prices.copy()

In [35]:
database["sell_price"] = database["sell_price"].round(2)

In [38]:
database.to_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/database_v5.csv", index=False, header=True, decimal=',', sep=';', float_format='%.3f')

In [39]:
gb = database.groupby(["id", "item", "category", "department", "store", "region", "year"]).sum()

In [40]:
gb.drop("sell_price", axis=1, inplace=True)

In [41]:
gb.reset_index(inplace=True)

In [42]:
gb

,id,item,category,department,store,region,year,units
0,ACCESORIES_1_001_BOS_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,Boston,2013,40
1,ACCESORIES_1_001_BOS_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,Boston,2014,92
2,ACCESORIES_1_001_BOS_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,Boston,2015,73
3,ACCESORIES_1_001_BOS_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,Boston,2016,17
4,ACCESORIES_1_001_BOS_2,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Roxbury,Boston,2013,56
...,...,...,...,...,...,...,...,...
155015,SUPERMARKET_3_827_PHI_2,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,Philadelphia,2015,345
155016,SUPERMARKET_3_827_PHI_2,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,Philadelphia,2016,136
155017,SUPERMARKET_3_827_PHI_3,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,Philadelphia,2014,495
155018,SUPERMARKET_3_827_PHI_3,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,Philadelphia,2015,526
155019,SUPERMARKET_3_827_PHI_3,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,Philadelphia,2016,70

In [43]:
gb.to_excel("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/db_powerbi_3.xlsx",header=True)

In [44]:
gb

,id,item,category,department,store,region,year,units
0,ACCESORIES_1_001_BOS_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,Boston,2013,40
1,ACCESORIES_1_001_BOS_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,Boston,2014,92
2,ACCESORIES_1_001_BOS_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,Boston,2015,73
3,ACCESORIES_1_001_BOS_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,Boston,2016,17
4,ACCESORIES_1_001_BOS_2,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Roxbury,Boston,2013,56
...,...,...,...,...,...,...,...,...
155015,SUPERMARKET_3_827_PHI_2,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,Philadelphia,2015,345
155016,SUPERMARKET_3_827_PHI_2,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,Philadelphia,2016,136
155017,SUPERMARKET_3_827_PHI_3,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,Philadelphia,2014,495
155018,SUPERMARKET_3_827_PHI_3,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,Philadelphia,2015,526
155019,SUPERMARKET_3_827_PHI_3,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,Philadelphia,2016,70

In [45]:
database.to_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/database_v5_floats.csv")

In [46]:
database

,id,units,item,category,department,store,store_code,region,date,sell_price,year,week
0,ACCESORIES_1_001_BOS_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,NaN,NaN,NaN
1,ACCESORIES_1_001_BOS_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Roxbury,BOS_2,Boston,2011-03-07,NaN,NaN,NaN
2,ACCESORIES_1_001_BOS_3,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07,NaN,NaN,NaN
3,ACCESORIES_1_001_NYC_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-03-07,NaN,NaN,NaN
4,ACCESORIES_1_001_NYC_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
8354255,SUPERMARKET_3_827_NYC_3,167,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Tribeca,NYC_3,New York,2016-02-29,NaN,NaN,NaN
8354256,SUPERMARKET_3_827_NYC_4,0,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Brooklyn,NYC_4,New York,2016-02-29,NaN,NaN,NaN
8354257,SUPERMARKET_3_827_PHI_1,36,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Midtown_Village,PHI_1,Philadelphia,2016-02-29,NaN,NaN,NaN
8354258,SUPERMARKET_3_827_PHI_2,21,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,PHI_2,Philadelphia,2016-02-29,NaN,NaN,NaN
8354259,SUPERMARKET_3_827_PHI_3,15,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-02-29,NaN,NaN,NaN

In [47]:
# sales_calendar_prices.to_csv("database_v2.csv")

In [48]:
# database = pd.read_csv(r"C:\Users\eduar\Downloads\dataset_v4.csv",sep=";")

In [49]:
# database.head()

In [50]:
# database["sell_price"] = database["sell_price"].round(2)

In [51]:
# database.to_csv("database_v5.csv")

In [52]:
# database.to_csv("database_v5.csv", index=False, header=True,
#               decimal=',', sep=';', float_format='%.3f')

In [53]:
# database[database["id"] == "ACCESORIES_1_002_BOS_1"]