In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Importar Sales Calendar
calendar = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD input/daily_calendar_with_events.csv")

#Importar Item Sales
sales = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD input/item_sales.csv")

#Importar Item Prices
prices = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD input/item_prices.csv")

In [4]:
sales

,id,item,category,department,store,store_code,region,d_1,d_2,d_3,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,ACCESORIES_1_001_NYC_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,ACCESORIES_1_002_NYC_1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,ACCESORIES_1_003_NYC_1,ACCESORIES_1_003,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,ACCESORIES_1_004_NYC_1,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,ACCESORIES_1_005_NYC_1,ACCESORIES_1_005,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,2,1,1,0,1,1,2,2,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30485,SUPERMARKET_3_823_PHI_3,SUPERMARKET_3_823,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,0,0,2,...,2,0,0,0,0,0,1,0,0,1
30486,SUPERMARKET_3_824_PHI_3,SUPERMARKET_3_824,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30487,SUPERMARKET_3_825_PHI_3,SUPERMARKET_3_825,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,0,6,0,...,2,1,0,2,0,1,0,0,1,0
30488,SUPERMARKET_3_826_PHI_3,SUPERMARKET_3_826,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,0,0,0,...,0,0,1,0,0,1,0,3,1,3
30489,SUPERMARKET_3_827_PHI_3,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
#Comprobación que tienen las mismas fechas
calendar_transpose = calendar.set_index("d").T
#Lista de "d" de "calendar"
lista = calendar_transpose.columns.tolist()
#Lista de "d" de "sales"
lista_1 = sales.columns.values.tolist()
lista_1 = lista_1[7:]
assert (lista == lista_1)

In [6]:
#Creación del diccionario con valores de "d" y de "date"
calendar_transpose_dates = calendar.set_index("date").T
lista_dates = calendar_transpose_dates.columns.tolist()
dict_dates = dict(zip(lista_1, lista_dates))

In [7]:
#Cambio de nombre de las columnas en la base de datos de "sales"
sales.rename(columns=dict_dates, inplace=True)
sales.head()

,id,item,category,department,store,store_code,region,2011-01-29,2011-01-30,2011-01-31,...,2016-04-15,2016-04-16,2016-04-17,2016-04-18,2016-04-19,2016-04-20,2016-04-21,2016-04-22,2016-04-23,2016-04-24
0,ACCESORIES_1_001_NYC_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,ACCESORIES_1_002_NYC_1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,ACCESORIES_1_003_NYC_1,ACCESORIES_1_003,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,ACCESORIES_1_004_NYC_1,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,ACCESORIES_1_005_NYC_1,ACCESORIES_1_005,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [8]:
sales_nan = sales.replace(0, np.nan)
sales_nan = sales.dropna(how='all', axis=0)

In [9]:
sales_nan

,id,item,category,department,store,store_code,region,2011-01-29,2011-01-30,2011-01-31,...,2016-04-15,2016-04-16,2016-04-17,2016-04-18,2016-04-19,2016-04-20,2016-04-21,2016-04-22,2016-04-23,2016-04-24
0,ACCESORIES_1_001_NYC_1,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,ACCESORIES_1_002_NYC_1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,ACCESORIES_1_003_NYC_1,ACCESORIES_1_003,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,ACCESORIES_1_004_NYC_1,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,ACCESORIES_1_005_NYC_1,ACCESORIES_1_005,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,0,0,0,...,2,1,1,0,1,1,2,2,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30485,SUPERMARKET_3_823_PHI_3,SUPERMARKET_3_823,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,0,0,2,...,2,0,0,0,0,0,1,0,0,1
30486,SUPERMARKET_3_824_PHI_3,SUPERMARKET_3_824,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30487,SUPERMARKET_3_825_PHI_3,SUPERMARKET_3_825,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,0,6,0,...,2,1,0,2,0,1,0,0,1,0
30488,SUPERMARKET_3_826_PHI_3,SUPERMARKET_3_826,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,0,0,0,...,0,0,1,0,0,1,0,3,1,3
30489,SUPERMARKET_3_827_PHI_3,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
#Creamos la lista de variables idenfiticadoras y variables de medidas.
lista = sales.columns.values.tolist()
lista_1 = lista[0:7]
del lista[0:7]
lista_1

['id', 'item', 'category', 'department', 'store', 'store_code', 'region']

In [11]:
sales = sales.melt(id_vars=lista_1, var_name="date", value_name= "units")

In [12]:
sales = sales.replace(0, np.nan)
sales.dropna(inplace= True)

In [13]:
sales

,id,item,category,department,store,store_code,region,date,units
7,ACCESORIES_1_008_NYC_1,ACCESORIES_1_008,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,12.0
8,ACCESORIES_1_009_NYC_1,ACCESORIES_1_009,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,2.0
14,ACCESORIES_1_015_NYC_1,ACCESORIES_1_015,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,4.0
15,ACCESORIES_1_016_NYC_1,ACCESORIES_1_016,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,5.0
21,ACCESORIES_1_022_NYC_1,ACCESORIES_1_022,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,2.0
...,...,...,...,...,...,...,...,...,...
58327361,SUPERMARKET_3_819_PHI_3,SUPERMARKET_3_819,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,2.0
58327362,SUPERMARKET_3_820_PHI_3,SUPERMARKET_3_820,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,1.0
58327364,SUPERMARKET_3_822_PHI_3,SUPERMARKET_3_822,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,1.0
58327365,SUPERMARKET_3_823_PHI_3,SUPERMARKET_3_823,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,1.0
58327368,SUPERMARKET_3_826_PHI_3,SUPERMARKET_3_826,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,3.0

In [14]:
calendar["date1"] = pd.to_datetime(calendar["date"], format = "%Y-%m-%d")
calendar["week"] = calendar["date1"].dt.isocalendar().week.astype(str)
calendar["year"] = calendar["date1"].dt.isocalendar().year.astype(str)
calendar["year_week"] = calendar["year"] + "-" + calendar["week"]

In [15]:
sales_calendar = pd.merge(
    left = sales,
    right = calendar,
    how = 'left',
    on = ["date"])

In [16]:
sales_calendar

,id,item,category,department,store,store_code,region,date,units,weekday,weekday_int,d,event,date1,week,year,year_week
0,ACCESORIES_1_008_NYC_1,ACCESORIES_1_008,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,12.0,Saturday,1,d_1,NaN,2011-01-29,4,2011,2011-4
1,ACCESORIES_1_009_NYC_1,ACCESORIES_1_009,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,2.0,Saturday,1,d_1,NaN,2011-01-29,4,2011,2011-4
2,ACCESORIES_1_015_NYC_1,ACCESORIES_1_015,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,4.0,Saturday,1,d_1,NaN,2011-01-29,4,2011,2011-4
3,ACCESORIES_1_016_NYC_1,ACCESORIES_1_016,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,5.0,Saturday,1,d_1,NaN,2011-01-29,4,2011,2011-4
4,ACCESORIES_1_022_NYC_1,ACCESORIES_1_022,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,2.0,Saturday,1,d_1,NaN,2011-01-29,4,2011,2011-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18550271,SUPERMARKET_3_819_PHI_3,SUPERMARKET_3_819,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,2.0,Sunday,2,d_1913,NaN,2016-04-24,16,2016,2016-16
18550272,SUPERMARKET_3_820_PHI_3,SUPERMARKET_3_820,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,1.0,Sunday,2,d_1913,NaN,2016-04-24,16,2016,2016-16
18550273,SUPERMARKET_3_822_PHI_3,SUPERMARKET_3_822,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,1.0,Sunday,2,d_1913,NaN,2016-04-24,16,2016,2016-16
18550274,SUPERMARKET_3_823_PHI_3,SUPERMARKET_3_823,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,1.0,Sunday,2,d_1913,NaN,2016-04-24,16,2016,2016-16
18550275,SUPERMARKET_3_826_PHI_3,SUPERMARKET_3_826,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,3.0,Sunday,2,d_1913,NaN,2016-04-24,16,2016,2016-16

In [17]:
sales_calendar["weekend_sales"] = np.where( (sales_calendar.weekday == "Saturday") | (sales_calendar.weekday == "Sunday"), sales_calendar.units, 0)

In [18]:
sales_calendar["event_dummy"] = sales_calendar.event.isnull().value_counts()

In [19]:
sales_calendar["event_sales"] = np.where( (sales_calendar.event_dummy == True), sales_calendar.units, 0)

In [20]:
sales_calendar

,id,item,category,department,store,store_code,region,date,units,weekday,weekday_int,d,event,date1,week,year,year_week,weekend_sales,event_dummy,event_sales
0,ACCESORIES_1_008_NYC_1,ACCESORIES_1_008,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,12.0,Saturday,1,d_1,NaN,2011-01-29,4,2011,2011-4,12.0,NaN,0.0
1,ACCESORIES_1_009_NYC_1,ACCESORIES_1_009,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,2.0,Saturday,1,d_1,NaN,2011-01-29,4,2011,2011-4,2.0,NaN,0.0
2,ACCESORIES_1_015_NYC_1,ACCESORIES_1_015,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,4.0,Saturday,1,d_1,NaN,2011-01-29,4,2011,2011-4,4.0,NaN,0.0
3,ACCESORIES_1_016_NYC_1,ACCESORIES_1_016,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,5.0,Saturday,1,d_1,NaN,2011-01-29,4,2011,2011-4,5.0,NaN,0.0
4,ACCESORIES_1_022_NYC_1,ACCESORIES_1_022,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-01-29,2.0,Saturday,1,d_1,NaN,2011-01-29,4,2011,2011-4,2.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18550271,SUPERMARKET_3_819_PHI_3,SUPERMARKET_3_819,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,2.0,Sunday,2,d_1913,NaN,2016-04-24,16,2016,2016-16,2.0,NaN,0.0
18550272,SUPERMARKET_3_820_PHI_3,SUPERMARKET_3_820,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,1.0,Sunday,2,d_1913,NaN,2016-04-24,16,2016,2016-16,1.0,NaN,0.0
18550273,SUPERMARKET_3_822_PHI_3,SUPERMARKET_3_822,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,1.0,Sunday,2,d_1913,NaN,2016-04-24,16,2016,2016-16,1.0,NaN,0.0
18550274,SUPERMARKET_3_823_PHI_3,SUPERMARKET_3_823,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,1.0,Sunday,2,d_1913,NaN,2016-04-24,16,2016,2016-16,1.0,NaN,0.0
18550275,SUPERMARKET_3_826_PHI_3,SUPERMARKET_3_826,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-24,3.0,Sunday,2,d_1913,NaN,2016-04-24,16,2016,2016-16,3.0,NaN,0.0

In [21]:
sales_calendar_weekly = sales_calendar.groupby(["id", "year", "week"]).sum()

In [22]:
sales_calendar_weekly.reset_index(inplace =True)

In [23]:
sales_calendar_weekly

,id,year,week,units,weekday_int,weekend_sales,event_dummy,event_sales
0,ACCESORIES_1_001_BOS_1,2013,29,4.0,9,0.0,0.0,0.0
1,ACCESORIES_1_001_BOS_1,2013,30,4.0,8,1.0,0.0,0.0
2,ACCESORIES_1_001_BOS_1,2013,31,2.0,3,0.0,0.0,0.0
3,ACCESORIES_1_001_BOS_1,2013,32,1.0,7,0.0,0.0,0.0
4,ACCESORIES_1_001_BOS_1,2013,35,2.0,10,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
4990893,SUPERMARKET_3_827_PHI_3,2016,5,9.0,25,3.0,0.0,0.0
4990894,SUPERMARKET_3_827_PHI_3,2016,6,17.0,19,3.0,0.0,0.0
4990895,SUPERMARKET_3_827_PHI_3,2016,7,9.0,20,2.0,0.0,0.0
4990896,SUPERMARKET_3_827_PHI_3,2016,8,9.0,15,4.0,0.0,0.0
4990897,SUPERMARKET_3_827_PHI_3,2016,9,15.0,22,3.0,0.0,0.0

In [24]:
sales_calendar_weekly.to_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/database_weekends_events_4.csv")

In [25]:
calendar["event"].value_counts()

SuperBowl         6
Ramadan starts    5
Thanksgiving      5
NewYear           5
Easter            5
Name: event, dtype: int64

In [26]:
prueba = prices.groupby(["item"]).first()

In [27]:
prueba = prices.groupby(["yearweek", "item", "store_code"]).first()

In [28]:
prueba.reset_index(inplace = True)

In [29]:
prueba_min = prueba.groupby(["yearweek", "item"]).min()

In [30]:
prueba_max = prueba.groupby(["yearweek", "item"]).max()

In [31]:
prueba_merge = pd.merge(
    left = prueba_min,
    right = prueba_max,
    how = 'left',
    on = ["yearweek", "item"])

In [32]:
prueba_merge

                           store_code_x   category_x  sell_price_x  \
yearweek item
201105.0 ACCESORIES_1_004         BOS_1   ACCESORIES        5.7722
         ACCESORIES_1_008         BOS_1   ACCESORIES        0.6118
         ACCESORIES_1_009         BOS_1   ACCESORIES        2.0748
         ACCESORIES_1_010         BOS_1   ACCESORIES        4.2161
         ACCESORIES_1_012         BOS_1   ACCESORIES        7.9534
...                                 ...          ...           ...
201617.0 SUPERMARKET_3_823        BOS_1  SUPERMARKET        3.5760
         SUPERMARKET_3_824        BOS_1  SUPERMARKET        2.9760
         SUPERMARKET_3_825        BOS_1  SUPERMARKET        4.7760
         SUPERMARKET_3_826        BOS_1  SUPERMARKET        1.5360
         SUPERMARKET_3_827        BOS_1  SUPERMARKET        1.2000

                           store_code_y   category_y  sell_price_y
yearweek item
201105.0 ACCESORIES_1_004         PHI_3   ACCESORIES        5.7722
         ACCESORIES_1_008         PHI_3   ACCESORIES        0.6650
         ACCESORIES_1_009         PHI_3   ACCESORIES        2.1280
         ACCESORIES_1_010         PHI_3   ACCESORIES        4.2161
         ACCESORIES_1_012         PHI_3   ACCESORIES        8.7514
...                                 ...          ...           ...
201617.0 SUPERMARKET_3_823        PHI_3  SUPERMARKET        3.5760
         SUPERMARKET_3_824        PHI_3  SUPERMARKET        2.9760
         SUPERMARKET_3_825        PHI_3  SUPERMARKET        4.7760
         SUPERMARKET_3_826        PHI_3  SUPERMARKET        1.5360
         SUPERMARKET_3_827        PHI_3  SUPERMARKET        1.2000

[701115 rows x 6 columns]