En este notebook se hace el preprocessing de "database_v5.csv" que pasar√° a convertirse en "database_v6.csv"

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import datetime
sns.set_theme(style='darkgrid')

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/database_v5_floats.csv")

In [ ]:
df

,Unnamed: 0,id,units,item,category,department,store,store_code,region,date,sell_price,year,week
0,0,ACCESORIES_1_001_BOS_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,NaN,NaN,NaN
1,1,ACCESORIES_1_001_BOS_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Roxbury,BOS_2,Boston,2011-03-07,NaN,NaN,NaN
2,2,ACCESORIES_1_001_BOS_3,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07,NaN,NaN,NaN
3,3,ACCESORIES_1_001_NYC_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-03-07,NaN,NaN,NaN
4,4,ACCESORIES_1_001_NYC_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8354255,8354255,SUPERMARKET_3_827_NYC_3,167,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Tribeca,NYC_3,New York,2016-02-29,NaN,NaN,NaN
8354256,8354256,SUPERMARKET_3_827_NYC_4,0,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Brooklyn,NYC_4,New York,2016-02-29,NaN,NaN,NaN
8354257,8354257,SUPERMARKET_3_827_PHI_1,36,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Midtown_Village,PHI_1,Philadelphia,2016-02-29,NaN,NaN,NaN
8354258,8354258,SUPERMARKET_3_827_PHI_2,21,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,PHI_2,Philadelphia,2016-02-29,NaN,NaN,NaN
8354259,8354259,SUPERMARKET_3_827_PHI_3,15,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-02-29,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8354260 entries, 0 to 8354259
Data columns (total 13 columns):
 #   Column      Dtype
---  ------      -----
 0   Unnamed: 0  int64
 1   id          object
 2   units       int64
 3   item        object
 4   category    object
 5   department  object
 6   store       object
 7   store_code  object
 8   region      object
 9   date        object
 10  sell_price  float64
 11  year        float64
 12  week        float64
dtypes: float64(3), int64(2), object(8)
memory usage: 828.6+ MB

In [ ]:
df.shape

(8354260, 13)

In [ ]:
df

,Unnamed: 0,id,units,item,category,department,store,store_code,region,date,sell_price,year,week
0,0,ACCESORIES_1_001_BOS_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,NaN,NaN,NaN
1,1,ACCESORIES_1_001_BOS_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Roxbury,BOS_2,Boston,2011-03-07,NaN,NaN,NaN
2,2,ACCESORIES_1_001_BOS_3,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07,NaN,NaN,NaN
3,3,ACCESORIES_1_001_NYC_1,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Greenwich_Village,NYC_1,New York,2011-03-07,NaN,NaN,NaN
4,4,ACCESORIES_1_001_NYC_2,0,ACCESORIES_1_001,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8354255,8354255,SUPERMARKET_3_827_NYC_3,167,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Tribeca,NYC_3,New York,2016-02-29,NaN,NaN,NaN
8354256,8354256,SUPERMARKET_3_827_NYC_4,0,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Brooklyn,NYC_4,New York,2016-02-29,NaN,NaN,NaN
8354257,8354257,SUPERMARKET_3_827_PHI_1,36,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Midtown_Village,PHI_1,Philadelphia,2016-02-29,NaN,NaN,NaN
8354258,8354258,SUPERMARKET_3_827_PHI_2,21,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,PHI_2,Philadelphia,2016-02-29,NaN,NaN,NaN
8354259,8354259,SUPERMARKET_3_827_PHI_3,15,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-02-29,NaN,NaN,NaN

In [ ]:
df.isnull().sum()

Unnamed: 0          0
id                  0
units               0
item                0
category            0
department          0
store               0
store_code          0
region              0
date                0
sell_price    3008732
year          3008732
week          3008732
dtype: int64

In [ ]:
for i in ["date"]:
    df[i]=pd.to_datetime(df[i])

In [ ]:
df_sin_duplicados = df.copy()

In [ ]:
df_sin_duplicados=df.drop_duplicates().copy(deep=True)

In [ ]:
df_sin_duplicados.reset_index(drop=True, inplace=True)

In [ ]:
df_sin_duplicados.shape

(8354260, 13)

In [ ]:
df_sin_duplicados.isnull().sum()

Unnamed: 0          0
id                  0
units               0
item                0
category            0
department          0
store               0
store_code          0
region              0
date                0
sell_price    3008732
year          3008732
week          3008732
dtype: int64

In [ ]:
# df_sin_duplicados['sales'].value_counts()

In [ ]:
df_sin_duplicados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8354260 entries, 0 to 8354259
Data columns (total 13 columns):
 #   Column      Dtype
---  ------      -----
 0   Unnamed: 0  int64
 1   id          object
 2   units       int64
 3   item        object
 4   category    object
 5   department  object
 6   store       object
 7   store_code  object
 8   region      object
 9   date        datetime64[ns]
 10  sell_price  float64
 11  year        float64
 12  week        float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(7)
memory usage: 828.6+ MB

In [ ]:
df_sin_duplicados.isnull().sum()

Unnamed: 0          0
id                  0
units               0
item                0
category            0
department          0
store               0
store_code          0
region              0
date                0
sell_price    3008732
year          3008732
week          3008732
dtype: int64

In [ ]:
pd.to_numeric(df_sin_duplicados['sell_price'], errors='coerce')

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
           ..
8354255   NaN
8354256   NaN
8354257   NaN
8354258   NaN
8354259   NaN
Name: sell_price, Length: 8354260, dtype: float64

In [ ]:
# len(df_sin_duplicados[df_sin_duplicados['sales'].isnull()])

In [ ]:
df_sinnulos = df_sin_duplicados.copy()

In [ ]:
df_sinnulos.dropna(inplace=True)

In [ ]:
df_sinnulos.isnull().sum()

Unnamed: 0    0
id            0
units         0
item          0
category      0
department    0
store         0
store_code    0
region        0
date          0
sell_price    0
year          0
week          0
dtype: int64

In [ ]:
df_sinnulos.shape

(5345528, 13)

In [ ]:
df_sinnulos.reset_index(drop=True, inplace=True)

In [ ]:
df_final = df_sinnulos.copy()

In [ ]:
df_final['sales'] = df_final['units'] * df_final['sell_price']

In [ ]:
df_final['year'] = df_final['year'].apply(int)

In [ ]:
df_final.head()

,Unnamed: 0,id,units,item,category,department,store,store_code,region,date,sell_price,year,week,sales
0,10,ACCESORIES_1_002_BOS_1,4,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.28,2011,10.0,21.12
1,12,ACCESORIES_1_002_BOS_3,2,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07,5.28,2011,10.0,10.56
2,14,ACCESORIES_1_002_NYC_2,1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07,5.28,2011,10.0,5.28
3,19,ACCESORIES_1_002_PHI_3,3,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Queen_Village,PHI_3,Philadelphia,2011-03-07,5.28,2011,10.0,15.84
4,30,ACCESORIES_1_004_BOS_1,4,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.77,2011,10.0,23.08

In [ ]:
del(df_final['Unnamed: 0'])

In [ ]:
df_final['week'] = df_final['week'].apply(int)

In [ ]:
df_final['month'] = pd.DatetimeIndex(df_final['date']).month

In [ ]:
df_final['day'] = pd.DatetimeIndex(df_final['date']).day

In [ ]:
df_final

,id,units,item,category,department,store,store_code,region,date,sell_price,year,week,sales,month,day
0,ACCESORIES_1_002_BOS_1,4,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.28,2011,10,21.12,3,7
1,ACCESORIES_1_002_BOS_3,2,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07,5.28,2011,10,10.56,3,7
2,ACCESORIES_1_002_NYC_2,1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07,5.28,2011,10,5.28,3,7
3,ACCESORIES_1_002_PHI_3,3,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Queen_Village,PHI_3,Philadelphia,2011-03-07,5.28,2011,10,15.84,3,7
4,ACCESORIES_1_004_BOS_1,4,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.77,2011,10,23.08,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5345523,SUPERMARKET_3_827_NYC_3,38,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Tribeca,NYC_3,New York,2016-04-18,1.20,2016,16,45.60,4,18
5345524,SUPERMARKET_3_827_NYC_4,22,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Brooklyn,NYC_4,New York,2016-04-18,1.20,2016,16,26.40,4,18
5345525,SUPERMARKET_3_827_PHI_1,15,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Midtown_Village,PHI_1,Philadelphia,2016-04-18,1.20,2016,16,18.00,4,18
5345526,SUPERMARKET_3_827_PHI_2,12,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,PHI_2,Philadelphia,2016-04-18,1.20,2016,16,14.40,4,18
5345527,SUPERMARKET_3_827_PHI_3,0,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-18,1.20,2016,16,0.00,4,18

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5345528 entries, 0 to 5345527
Data columns (total 15 columns):
 #   Column      Dtype
---  ------      -----
 0   id          object
 1   units       int64
 2   item        object
 3   category    object
 4   department  object
 5   store       object
 6   store_code  object
 7   region      object
 8   date        datetime64[ns]
 9   sell_price  float64
 10  year        int64
 11  week        int64
 12  sales       float64
 13  month       int64
 14  day         int64
dtypes: datetime64[ns](1), float64(2), int64(5), object(7)
memory usage: 611.7+ MB

In [ ]:
df_final.shape

(5345528, 15)

In [ ]:
df_final['item'].unique()

array(['ACCESORIES_1_002', 'ACCESORIES_1_004', 'ACCESORIES_1_008', ...,
       'SUPERMARKET_3_563', 'SUPERMARKET_3_647', 'HOME_&_GARDEN_1_159'],
      dtype=object)

In [ ]:
df_final.groupby(['item','store','year'])['sales'].sum()

item               store     year
ACCESORIES_1_001   Back_Bay  2013     544.81
                             2014     863.78
                             2015    1703.45
                             2016     219.80
                   Brooklyn  2013     897.19
                                      ...
SUPERMARKET_3_827  Tribeca   2015     842.40
                             2016     372.00
                   Yorktown  2014      86.40
                             2015     414.00
                             2016     163.20
Name: sales, Length: 155020, dtype: float64

In [ ]:
df_final

,id,units,item,category,department,store,store_code,region,date,sell_price,year,week,sales,month,day
0,ACCESORIES_1_002_BOS_1,4,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.28,2011,10,21.12,3,7
1,ACCESORIES_1_002_BOS_3,2,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07,5.28,2011,10,10.56,3,7
2,ACCESORIES_1_002_NYC_2,1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07,5.28,2011,10,5.28,3,7
3,ACCESORIES_1_002_PHI_3,3,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Queen_Village,PHI_3,Philadelphia,2011-03-07,5.28,2011,10,15.84,3,7
4,ACCESORIES_1_004_BOS_1,4,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.77,2011,10,23.08,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5345523,SUPERMARKET_3_827_NYC_3,38,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Tribeca,NYC_3,New York,2016-04-18,1.20,2016,16,45.60,4,18
5345524,SUPERMARKET_3_827_NYC_4,22,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Brooklyn,NYC_4,New York,2016-04-18,1.20,2016,16,26.40,4,18
5345525,SUPERMARKET_3_827_PHI_1,15,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Midtown_Village,PHI_1,Philadelphia,2016-04-18,1.20,2016,16,18.00,4,18
5345526,SUPERMARKET_3_827_PHI_2,12,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,PHI_2,Philadelphia,2016-04-18,1.20,2016,16,14.40,4,18
5345527,SUPERMARKET_3_827_PHI_3,0,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-18,1.20,2016,16,0.00,4,18

In [ ]:
weekend = pd.read_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/database_weekends_events_4.csv")

In [ ]:
del(weekend["Unnamed: 0"])

In [ ]:
weekend

,id,year,week,units,weekday_int,weekend_sales,event_dummy,event_sales
0,ACCESORIES_1_001_BOS_1,2013,29,4.0,9,0.0,0.0,0.0
1,ACCESORIES_1_001_BOS_1,2013,30,4.0,8,1.0,0.0,0.0
2,ACCESORIES_1_001_BOS_1,2013,31,2.0,3,0.0,0.0,0.0
3,ACCESORIES_1_001_BOS_1,2013,32,1.0,7,0.0,0.0,0.0
4,ACCESORIES_1_001_BOS_1,2013,35,2.0,10,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
4990893,SUPERMARKET_3_827_PHI_3,2016,5,9.0,25,3.0,0.0,0.0
4990894,SUPERMARKET_3_827_PHI_3,2016,6,17.0,19,3.0,0.0,0.0
4990895,SUPERMARKET_3_827_PHI_3,2016,7,9.0,20,2.0,0.0,0.0
4990896,SUPERMARKET_3_827_PHI_3,2016,8,9.0,15,4.0,0.0,0.0
4990897,SUPERMARKET_3_827_PHI_3,2016,9,15.0,22,3.0,0.0,0.0

In [ ]:
df_final

,id,units,item,category,department,store,store_code,region,date,sell_price,year,week,sales,month,day
0,ACCESORIES_1_002_BOS_1,4,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.28,2011,10,21.12,3,7
1,ACCESORIES_1_002_BOS_3,2,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07,5.28,2011,10,10.56,3,7
2,ACCESORIES_1_002_NYC_2,1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07,5.28,2011,10,5.28,3,7
3,ACCESORIES_1_002_PHI_3,3,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Queen_Village,PHI_3,Philadelphia,2011-03-07,5.28,2011,10,15.84,3,7
4,ACCESORIES_1_004_BOS_1,4,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.77,2011,10,23.08,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5345523,SUPERMARKET_3_827_NYC_3,38,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Tribeca,NYC_3,New York,2016-04-18,1.20,2016,16,45.60,4,18
5345524,SUPERMARKET_3_827_NYC_4,22,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Brooklyn,NYC_4,New York,2016-04-18,1.20,2016,16,26.40,4,18
5345525,SUPERMARKET_3_827_PHI_1,15,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Midtown_Village,PHI_1,Philadelphia,2016-04-18,1.20,2016,16,18.00,4,18
5345526,SUPERMARKET_3_827_PHI_2,12,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,PHI_2,Philadelphia,2016-04-18,1.20,2016,16,14.40,4,18
5345527,SUPERMARKET_3_827_PHI_3,0,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-18,1.20,2016,16,0.00,4,18

In [ ]:
df_final = pd.merge(
    left = df_final,
    right = weekend,
    how = 'left',
    on = ["id", "year", "week"])

In [ ]:
df_final

,id,units_x,item,category,department,store,store_code,region,date,sell_price,year,week,sales,month,day,units_y,weekday_int,weekend_sales,event_dummy,event_sales
0,ACCESORIES_1_002_BOS_1,4,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.28,2011,10,21.12,3,7,4.0,15.0,2.0,0.0,0.0
1,ACCESORIES_1_002_BOS_3,2,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07,5.28,2011,10,10.56,3,7,2.0,8.0,1.0,0.0,0.0
2,ACCESORIES_1_002_NYC_2,1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07,5.28,2011,10,5.28,3,7,1.0,1.0,1.0,0.0,0.0
3,ACCESORIES_1_002_PHI_3,3,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Queen_Village,PHI_3,Philadelphia,2011-03-07,5.28,2011,10,15.84,3,7,3.0,6.0,1.0,0.0,0.0
4,ACCESORIES_1_004_BOS_1,4,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.77,2011,10,23.08,3,7,4.0,12.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5345523,SUPERMARKET_3_827_NYC_3,38,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Tribeca,NYC_3,New York,2016-04-18,1.20,2016,16,45.60,4,18,38.0,28.0,16.0,0.0,0.0
5345524,SUPERMARKET_3_827_NYC_4,22,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Brooklyn,NYC_4,New York,2016-04-18,1.20,2016,16,26.40,4,18,22.0,20.0,12.0,0.0,0.0
5345525,SUPERMARKET_3_827_PHI_1,15,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Midtown_Village,PHI_1,Philadelphia,2016-04-18,1.20,2016,16,18.00,4,18,15.0,25.0,0.0,0.0,0.0
5345526,SUPERMARKET_3_827_PHI_2,12,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,PHI_2,Philadelphia,2016-04-18,1.20,2016,16,14.40,4,18,12.0,19.0,2.0,0.0,0.0
5345527,SUPERMARKET_3_827_PHI_3,0,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-18,1.20,2016,16,0.00,4,18,NaN,NaN,NaN,NaN,NaN

In [ ]:
del(df_final["units_y"])

In [ ]:
df_final["units"] = df_final["units_x"]
del(df_final["units_x"])

In [ ]:
df_final = df_final.replace(np.nan, 0)

In [ ]:
df_final.isnull().sum()

id               0
item             0
category         0
department       0
store            0
store_code       0
region           0
date             0
sell_price       0
year             0
week             0
sales            0
month            0
day              0
weekday_int      0
weekend_sales    0
event_dummy      0
event_sales      0
units            0
dtype: int64

In [ ]:
df_final

,id,item,category,department,store,store_code,region,date,sell_price,year,week,sales,month,day,weekday_int,weekend_sales,event_dummy,event_sales,units
0,ACCESORIES_1_002_BOS_1,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.28,2011,10,21.12,3,7,15.0,2.0,0.0,0.0,4
1,ACCESORIES_1_002_BOS_3,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Back_Bay,BOS_3,Boston,2011-03-07,5.28,2011,10,10.56,3,7,8.0,1.0,0.0,0.0,2
2,ACCESORIES_1_002_NYC_2,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Harlem,NYC_2,New York,2011-03-07,5.28,2011,10,5.28,3,7,1.0,1.0,0.0,0.0,1
3,ACCESORIES_1_002_PHI_3,ACCESORIES_1_002,ACCESORIES,ACCESORIES_1,Queen_Village,PHI_3,Philadelphia,2011-03-07,5.28,2011,10,15.84,3,7,6.0,1.0,0.0,0.0,3
4,ACCESORIES_1_004_BOS_1,ACCESORIES_1_004,ACCESORIES,ACCESORIES_1,South_End,BOS_1,Boston,2011-03-07,5.77,2011,10,23.08,3,7,12.0,1.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5345523,SUPERMARKET_3_827_NYC_3,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Tribeca,NYC_3,New York,2016-04-18,1.20,2016,16,45.60,4,18,28.0,16.0,0.0,0.0,38
5345524,SUPERMARKET_3_827_NYC_4,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Brooklyn,NYC_4,New York,2016-04-18,1.20,2016,16,26.40,4,18,20.0,12.0,0.0,0.0,22
5345525,SUPERMARKET_3_827_PHI_1,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Midtown_Village,PHI_1,Philadelphia,2016-04-18,1.20,2016,16,18.00,4,18,25.0,0.0,0.0,0.0,15
5345526,SUPERMARKET_3_827_PHI_2,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Yorktown,PHI_2,Philadelphia,2016-04-18,1.20,2016,16,14.40,4,18,19.0,2.0,0.0,0.0,12
5345527,SUPERMARKET_3_827_PHI_3,SUPERMARKET_3_827,SUPERMARKET,SUPERMARKET_3,Queen_Village,PHI_3,Philadelphia,2016-04-18,1.20,2016,16,0.00,4,18,0.0,0.0,0.0,0.0,0

In [ ]:
df_final["summer_sales"] = np.where( (df_final.month == 6) |  (df_final.month == 7) |  (df_final.month == 8) , df_final.units, 0)

In [ ]:
df_final["christmas_sales"] = np.where( (df_final.month == 12) , df_final.units, 0)

In [ ]:
df_final_nan = df_final[ (df_final["units"]) == 0]
print(len(df_final))
print(len(df_final_nan))

5345528
1302730

In [ ]:
min_max_dates = df_final_nan.groupby(["item"]).agg({'date' : [np.min, np.max]}).reset_index()

In [ ]:
min_max_dates.columns = range(min_max_dates.shape[1])

In [ ]:
lista_1 = ["item", "min", "max"]
lista_dates = min_max_dates.columns.tolist()
dict_dates = dict(zip(lista_dates, lista_1))
min_max_dates.rename( columns =dict_dates, inplace = True)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5345528 entries, 0 to 5345527
Data columns (total 21 columns):
 #   Column           Dtype
---  ------           -----
 0   id               object
 1   item             object
 2   category         object
 3   department       object
 4   store            object
 5   store_code       object
 6   region           object
 7   date             datetime64[ns]
 8   sell_price       float64
 9   year             int64
 10  week             int64
 11  sales            float64
 12  month            int64
 13  day              int64
 14  weekday_int      float64
 15  weekend_sales    float64
 16  event_dummy      float64
 17  event_sales      float64
 18  units            int64
 19  summer_sales     int64
 20  christmas_sales  int64
dtypes: datetime64[ns](1), float64(6), int64(7), object(7)
memory usage: 897.2+ MB

In [ ]:
precio_inicio = df_final.groupby(["item", "date"]).max("sell_price").reset_index()

In [ ]:
precio_inicio["min"] = precio_inicio["date"]

In [ ]:
precio_inicio = precio_inicio[["item", "min", "sell_price"]]

In [ ]:
precios = pd.merge(
    left = min_max_dates,
    right = precio_inicio,
    how = 'left',
    on = ["item", "min"])

In [ ]:
precios.rename(columns = {"sell_price" : "precio_inicio" })

                   item        min        max  precio_inicio
0      ACCESORIES_1_001 2013-07-08 2016-04-18          12.74
1      ACCESORIES_1_002 2011-03-14 2016-04-18           5.28
2      ACCESORIES_1_003 2014-03-03 2016-04-18           3.95
3      ACCESORIES_1_004 2011-03-14 2016-04-04           5.77
4      ACCESORIES_1_005 2011-05-23 2015-11-23           3.96
...                 ...        ...        ...            ...
3040  SUPERMARKET_3_823 2011-05-16 2016-04-04           3.58
3041  SUPERMARKET_3_824 2011-03-07 2016-04-18           2.98
3042  SUPERMARKET_3_825 2011-03-07 2016-03-21           4.80
3043  SUPERMARKET_3_826 2013-03-25 2016-03-21           1.54
3044  SUPERMARKET_3_827 2014-03-10 2016-04-18           1.20

[3045 rows x 4 columns]

In [ ]:
precios['exhibition_time'] = (precios['max'] - precios['min']).dt.days

In [ ]:
items_sales = df_final.groupby("item").sum()

In [ ]:
items_sales

,sell_price,year,week,sales,month,day,weekday_int,weekend_sales,event_dummy,event_sales,units,summer_sales,christmas_sales
item,,,,,,,,,,,,,
ACCESORIES_1_001,12895.14,2352684,37227,35910.09,8866,18325,9026.0,1099.0,0.0,0.0,3263,867,338
ACCESORIES_1_002,11448.37,4366509,66687,22869.01,15997,33727,12859.0,1517.0,0.0,0.0,4332,1254,809
ACCESORIES_1_003,3500.83,1789002,26289,4482.89,6274,13886,3521.0,424.0,0.0,0.0,1139,315,157
ACCESORIES_1_004,13246.74,4457004,67493,190523.01,16202,34389,38002.0,11305.0,0.0,0.0,31711,9117,2794
ACCESORIES_1_005,8094.83,4247860,65780,45395.37,15763,32848,24465.0,4225.0,0.0,0.0,11912,3629,1230
...,...,...,...,...,...,...,...,...,...,...,...,...,...
SUPERMARKET_3_823,7137.40,4290069,65452,40432.09,15702,33060,18286.0,4208.0,0.0,0.0,12211,3458,1266
SUPERMARKET_3_824,6732.76,4469070,67560,21651.76,16220,34480,16485.0,2294.0,0.0,0.0,7077,2441,375
SUPERMARKET_3_825,10955.83,4469070,67560,51628.55,16220,34480,22585.0,3615.0,0.0,0.0,10613,3403,822
SUPERMARKET_3_826,1987.80,2600283,39841,15437.48,9508,20144,18737.0,3073.0,0.0,0.0,10025,3366,722
SUPERMARKET_3_827,944.40,1585588,23998,10436.40,5719,12333,9282.0,3042.0,0.0,0.0,8697,2088,646

Discount

In [ ]:
from datetime import datetime, timedelta

In [ ]:
last_week = df_final.groupby(["date", "item"]).min()
last_week.reset_index(inplace = True)

In [ ]:
last_week["date_last_week"] = last_week["date"] - timedelta(days = 7 )

In [ ]:
lista = last_week.columns.tolist()
lista
lista.remove("date")
lista.remove("item")
lista.remove("date_last_week")
lista.remove("sell_price")
for i in lista: 
    del(last_week[i])

In [ ]:
discount = df_final.groupby(["date", "item"]).min()
discount.reset_index (inplace = True)

In [ ]:
lista = discount.columns.tolist()
lista
lista.remove("date")
lista.remove("item")
lista.remove("sell_price")
for i in lista: 
    del(discount[i])

In [ ]:
discount.rename(columns = {"date" : "date_last_week" }, inplace=True)

In [ ]:
first_discount = pd.merge(
    left = last_week,
    right = discount,
    how = 'left',
    on = ["date_last_week", "item"])

In [ ]:
first_discount.rename(columns = {"sell_price_y" : "precio_last_week" }, inplace=True)

In [ ]:
first_discount["cambio"] = first_discount["precio_last_week"]- first_discount["sell_price_x"]

In [ ]:
first_discount.groupby("cambio").first()
first_discount.reset_index(inplace = True)

In [ ]:
first_discount["discount"] = first_discount["precio_last_week"] / first_discount["sell_price_x"]-1

In [ ]:
first_discount["discount"] = np.where( (first_discount.discount < -0.05) , first_discount.discount, 0)

In [ ]:
first_discount = first_discount[ (first_discount["discount"]) != 0]

In [ ]:
first_discount = first_discount.sort_values(by="date").groupby("item").first()

In [ ]:
first_discount.reset_index (inplace = True)
lista = ["date", "sell_price_x", "cambio", "index"]
for i in lista:
    del(first_discount[i])

In [ ]:
precios_discounts = pd.merge(
    left = precios,
    right = first_discount,
    how = 'left',
    on = ["item"])

In [ ]:
precios_discounts['days_until_first_discount'] = (precios_discounts['date_last_week'] - precios_discounts['min']).dt.days

In [ ]:
precios_discounts

,item,min,max,sell_price,exhibition_time,date_last_week,precio_last_week,discount,days_until_first_discount
0,ACCESORIES_1_001,2013-07-08,2016-04-18,12.74,1015,2015-06-29,6.65,-0.394904,721.0
1,ACCESORIES_1_002,2011-03-14,2016-04-18,5.28,1862,2014-09-15,3.95,-0.251894,1281.0
2,ACCESORIES_1_003,2014-03-03,2016-04-18,3.95,777,2014-04-07,1.25,-0.683544,35.0
3,ACCESORIES_1_004,2011-03-14,2016-04-04,5.77,1848,NaT,NaN,NaN,NaN
4,ACCESORIES_1_005,2011-05-23,2015-11-23,3.96,1645,2012-04-09,3.30,-0.090909,322.0
...,...,...,...,...,...,...,...,...,...
3040,SUPERMARKET_3_823,2011-05-16,2016-04-04,3.58,1785,2011-05-09,3.00,-0.162011,-7.0
3041,SUPERMARKET_3_824,2011-03-07,2016-04-18,2.98,1869,2013-09-16,2.40,-0.083969,924.0
3042,SUPERMARKET_3_825,2011-03-07,2016-03-21,4.80,1841,2011-10-10,4.78,-0.091255,217.0
3043,SUPERMARKET_3_826,2013-03-25,2016-03-21,1.54,1092,2014-03-24,1.20,-0.220779,364.0
3044,SUPERMARKET_3_827,2014-03-10,2016-04-18,1.20,770,NaT,NaN,NaN,NaN

In [ ]:
precio_first = precios_discounts.groupby("item").first("sell.price")

In [ ]:
del(precio_first["exhibition_time"])
del(precio_first["precio_last_week"])
del(precio_first["discount"])
del(precio_first["days_until_first_discount"])
precio_first.rename(columns = {"sell_price" : "precio_inicio" }, inplace=True)

In [ ]:
dias_fp = pd.merge(
    left = precio_inicio,
    right = precio_first,
    how = 'left',
    on = ["item"])

In [ ]:
dias_fp["discount_on_date"] = dias_fp["sell_price"]- dias_fp["precio_inicio"]

In [ ]:
dias_fp["full_price_dummy"] = np.where( (dias_fp.discount_on_date == 0) , 1, 0)

In [ ]:
fp_days = dias_fp.groupby("item").sum()
fp_days.reset_index(inplace =True)

In [ ]:
fp_days

,item,sell_price,precio_inicio,discount_on_date,full_price_dummy
0,ACCESORIES_1_001,1332.41,1503.32,-170.91,7
1,ACCESORIES_1_002,1172.16,1172.16,0.00,222
2,ACCESORIES_1_003,371.34,367.35,3.99,92
3,ACCESORIES_1_004,1335.34,1280.94,54.40,86
4,ACCESORIES_1_005,842.28,847.44,-5.16,84
...,...,...,...,...,...
3044,SUPERMARKET_3_823,752.80,794.76,-41.96,65
3045,SUPERMARKET_3_824,703.80,661.56,42.24,46
3046,SUPERMARKET_3_825,1100.90,1065.60,35.30,19
3047,SUPERMARKET_3_826,204.82,204.82,0.00,133
3048,SUPERMARKET_3_827,111.60,111.60,0.00,93

In [ ]:
del(fp_days["sell_price"])
del(fp_days["precio_inicio"])
del(fp_days["discount_on_date"])

In [ ]:
precios_discount_fp = pd.merge(
    left = precios_discounts,
    right = fp_days,
    how = 'left',
    on = ["item"])

In [ ]:
del(precios_discount_fp["date_last_week"])
del(precios_discount_fp["precio_last_week"])
precios_discount_fp.rename(columns = {"sell_price" : "precio_inicio", "min" : "fecha_inicio_venta", "max": "fecha_fin_venta", "discount" : "first_discount"  }, inplace=True)

In [ ]:
precios_discount_fp

,item,fecha_inicio_venta,fecha_fin_venta,precio_inicio,exhibition_time,first_discount,days_until_first_discount,full_price_dummy
0,ACCESORIES_1_001,2013-07-08,2016-04-18,12.74,1015,-0.394904,721.0,7
1,ACCESORIES_1_002,2011-03-14,2016-04-18,5.28,1862,-0.251894,1281.0,222
2,ACCESORIES_1_003,2014-03-03,2016-04-18,3.95,777,-0.683544,35.0,92
3,ACCESORIES_1_004,2011-03-14,2016-04-04,5.77,1848,NaN,NaN,86
4,ACCESORIES_1_005,2011-05-23,2015-11-23,3.96,1645,-0.090909,322.0,84
...,...,...,...,...,...,...,...,...
3040,SUPERMARKET_3_823,2011-05-16,2016-04-04,3.58,1785,-0.162011,-7.0,65
3041,SUPERMARKET_3_824,2011-03-07,2016-04-18,2.98,1869,-0.083969,924.0,46
3042,SUPERMARKET_3_825,2011-03-07,2016-03-21,4.80,1841,-0.091255,217.0,19
3043,SUPERMARKET_3_826,2013-03-25,2016-03-21,1.54,1092,-0.220779,364.0,133
3044,SUPERMARKET_3_827,2014-03-10,2016-04-18,1.20,770,NaN,NaN,93

In [ ]:
df_final["sales_2011"] = np.where( (df_final.year == 2011) , df_final.units, 0)
df_final["sales_2012"] = np.where( (df_final.year == 2012) , df_final.units, 0)
df_final["sales_2013"] = np.where( (df_final.year == 2013) , df_final.units, 0)
df_final["sales_2014"] = np.where( (df_final.year == 2014) , df_final.units, 0)
df_final["sales_2015"] = np.where( (df_final.year == 2015) , df_final.units, 0)
df_final["sales_2016"] = np.where( (df_final.year == 2016) , df_final.units, 0)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5345528 entries, 0 to 5345527
Data columns (total 27 columns):
 #   Column           Dtype
---  ------           -----
 0   id               object
 1   item             object
 2   category         object
 3   department       object
 4   store            object
 5   store_code       object
 6   region           object
 7   date             datetime64[ns]
 8   sell_price       float64
 9   year             int64
 10  week             int64
 11  sales            float64
 12  month            int64
 13  day              int64
 14  weekday_int      float64
 15  weekend_sales    float64
 16  event_dummy      float64
 17  event_sales      float64
 18  units            int64
 19  summer_sales     int64
 20  christmas_sales  int64
 21  sales_2011       int64
 22  sales_2012       int64
 23  sales_2013       int64
 24  sales_2014       int64
 25  sales_2015       int64
 26  sales_2016       int64
dtypes: datetime64[ns](1), float64(6), int64(13), object(7)
memory usage: 1.1+ GB

In [ ]:
df_final.to_csv("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/DF_FINAL.csv")  # este archivo va al sales forecast

In [ ]:
items_sales = df_final.groupby(["item","category"]).sum()
items_sales.reset_index(inplace = True)
list = ["year", "week", "month", "day", "weekday_int"]
for i in list: 
    del(items_sales[i])

In [ ]:
items_sales["mean_pvp"] = items_sales["sales"] / items_sales ["units"]

In [ ]:
items_sales["weekend_sale_total"] = items_sales["weekend_sales"] / items_sales ["sales"]

In [ ]:
items_sales["event_sales_total"] = items_sales["event_sales"] / items_sales ["sales"]

In [ ]:
items_sales["summer_sales_total"] = items_sales["summer_sales"] / items_sales ["sales"]

In [ ]:
items_sales["christmas_sales_total"] = items_sales["christmas_sales"] / items_sales ["sales"]

In [ ]:
items_sales["2015_vs_2014"] = items_sales["sales_2015"] / items_sales ["sales_2014"]-1

In [ ]:
items_sales["2015_vs_2013"] = items_sales["sales_2015"] / items_sales ["sales_2014"]-1

In [ ]:
items_sales

,item,category,sell_price,sales,weekend_sales,event_dummy,event_sales,units,summer_sales,christmas_sales,...,sales_2014,sales_2015,sales_2016,mean_pvp,weekend_sale_total,event_sales_total,summer_sales_total,christmas_sales_total,2015_vs_2014,2015_vs_2013
0,ACCESORIES_1_001,ACCESORIES,12895.14,35910.09,1099.0,0.0,0.0,3263,867,338,...,1062,1343,274,11.005238,0.030604,0.0,0.024144,0.009412,0.264595,0.264595
1,ACCESORIES_1_002,ACCESORIES,11448.37,22869.01,1517.0,0.0,0.0,4332,1254,809,...,848,850,120,5.279088,0.066334,0.0,0.054834,0.035375,0.002358,0.002358
2,ACCESORIES_1_003,ACCESORIES,3500.83,4482.89,424.0,0.0,0.0,1139,315,157,...,318,686,135,3.935812,0.094582,0.0,0.070267,0.035022,1.157233,1.157233
3,ACCESORIES_1_004,ACCESORIES,13246.74,190523.01,11305.0,0.0,0.0,31711,9117,2794,...,7102,5624,795,6.008105,0.059337,0.0,0.047852,0.014665,-0.208110,-0.208110
4,ACCESORIES_1_005,ACCESORIES,8094.83,45395.37,4225.0,0.0,0.0,11912,3629,1230,...,1849,2628,501,3.810894,0.093071,0.0,0.079942,0.027095,0.421309,0.421309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3044,SUPERMARKET_3_823,SUPERMARKET,7137.40,40432.09,4208.0,0.0,0.0,12211,3458,1266,...,1746,3877,245,3.311120,0.104076,0.0,0.085526,0.031312,1.220504,1.220504
3045,SUPERMARKET_3_824,SUPERMARKET,6732.76,21651.76,2294.0,0.0,0.0,7077,2441,375,...,1463,289,140,3.059455,0.105950,0.0,0.112739,0.017320,-0.802461,-0.802461
3046,SUPERMARKET_3_825,SUPERMARKET,10955.83,51628.55,3615.0,0.0,0.0,10613,3403,822,...,2429,2395,538,4.864652,0.070019,0.0,0.065913,0.015921,-0.013998,-0.013998
3047,SUPERMARKET_3_826,SUPERMARKET,1987.80,15437.48,3073.0,0.0,0.0,10025,3366,722,...,3271,3031,649,1.539898,0.199061,0.0,0.218041,0.046769,-0.073372,-0.073372
3048,SUPERMARKET_3_827,SUPERMARKET,944.40,10436.40,3042.0,0.0,0.0,8697,2088,646,...,2697,4664,1336,1.200000,0.291480,0.0,0.200069,0.061899,0.729329,0.729329

In [ ]:
df_cluster = pd.merge(
    left = items_sales,
    right = precios_discount_fp,
    how = 'left',
    on = ["item"])

In [ ]:
df_cluster["full_price_sales"] = df_cluster["precio_inicio"] * df_cluster["units"]
df_cluster["mean_discount"] = df_cluster["sales"] / df_cluster["full_price_sales"]-1

In [ ]:
df_cluster

,item,category,sell_price,sales,weekend_sales,event_dummy,event_sales,units,summer_sales,christmas_sales,...,2015_vs_2013,fecha_inicio_venta,fecha_fin_venta,precio_inicio,exhibition_time,first_discount,days_until_first_discount,full_price_dummy,full_price_sales,mean_discount
0,ACCESORIES_1_001,ACCESORIES,12895.14,35910.09,1099.0,0.0,0.0,3263,867,338,...,0.264595,2013-07-08,2016-04-18,12.74,1015.0,-0.394904,721.0,7.0,41570.62,-0.136167
1,ACCESORIES_1_002,ACCESORIES,11448.37,22869.01,1517.0,0.0,0.0,4332,1254,809,...,0.002358,2011-03-14,2016-04-18,5.28,1862.0,-0.251894,1281.0,222.0,22872.96,-0.000173
2,ACCESORIES_1_003,ACCESORIES,3500.83,4482.89,424.0,0.0,0.0,1139,315,157,...,1.157233,2014-03-03,2016-04-18,3.95,777.0,-0.683544,35.0,92.0,4499.05,-0.003592
3,ACCESORIES_1_004,ACCESORIES,13246.74,190523.01,11305.0,0.0,0.0,31711,9117,2794,...,-0.208110,2011-03-14,2016-04-04,5.77,1848.0,NaN,NaN,86.0,182972.47,0.041266
4,ACCESORIES_1_005,ACCESORIES,8094.83,45395.37,4225.0,0.0,0.0,11912,3629,1230,...,0.421309,2011-05-23,2015-11-23,3.96,1645.0,-0.090909,322.0,84.0,47171.52,-0.037653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3044,SUPERMARKET_3_823,SUPERMARKET,7137.40,40432.09,4208.0,0.0,0.0,12211,3458,1266,...,1.220504,2011-05-16,2016-04-04,3.58,1785.0,-0.162011,-7.0,65.0,43715.38,-0.075106
3045,SUPERMARKET_3_824,SUPERMARKET,6732.76,21651.76,2294.0,0.0,0.0,7077,2441,375,...,-0.802461,2011-03-07,2016-04-18,2.98,1869.0,-0.083969,924.0,46.0,21089.46,0.026663
3046,SUPERMARKET_3_825,SUPERMARKET,10955.83,51628.55,3615.0,0.0,0.0,10613,3403,822,...,-0.013998,2011-03-07,2016-03-21,4.80,1841.0,-0.091255,217.0,19.0,50942.40,0.013469
3047,SUPERMARKET_3_826,SUPERMARKET,1987.80,15437.48,3073.0,0.0,0.0,10025,3366,722,...,-0.073372,2013-03-25,2016-03-21,1.54,1092.0,-0.220779,364.0,133.0,15438.50,-0.000066
3048,SUPERMARKET_3_827,SUPERMARKET,944.40,10436.40,3042.0,0.0,0.0,8697,2088,646,...,0.729329,2014-03-10,2016-04-18,1.20,770.0,NaN,NaN,93.0,10436.40,0.000000

In [ ]:
del(df_cluster["sell_price"])
del(df_cluster["weekend_sales"])
del(df_cluster["event_sales"])
del(df_cluster["summer_sales"])
del(df_cluster["sales_2015"])
del(df_cluster["sales_2011"])
del(df_cluster["sales_2014"])
del(df_cluster["sales_2013"])
del(df_cluster["sales_2012"])
del(df_cluster["sales_2016"])
del(df_cluster["fecha_inicio_venta"])
del(df_cluster["fecha_fin_venta"])
del(df_cluster["christmas_sales"])
del(df_cluster["event_dummy"])

In [ ]:
df_cluster

,item,category,sales,units,mean_pvp,weekend_sale_total,event_sales_total,summer_sales_total,christmas_sales_total,2015_vs_2014,2015_vs_2013,precio_inicio,exhibition_time,first_discount,days_until_first_discount,full_price_dummy,full_price_sales,mean_discount
0,ACCESORIES_1_001,ACCESORIES,35910.09,3263,11.005238,0.030604,0.0,0.024144,0.009412,0.264595,0.264595,12.74,1015.0,-0.394904,721.0,7.0,41570.62,-0.136167
1,ACCESORIES_1_002,ACCESORIES,22869.01,4332,5.279088,0.066334,0.0,0.054834,0.035375,0.002358,0.002358,5.28,1862.0,-0.251894,1281.0,222.0,22872.96,-0.000173
2,ACCESORIES_1_003,ACCESORIES,4482.89,1139,3.935812,0.094582,0.0,0.070267,0.035022,1.157233,1.157233,3.95,777.0,-0.683544,35.0,92.0,4499.05,-0.003592
3,ACCESORIES_1_004,ACCESORIES,190523.01,31711,6.008105,0.059337,0.0,0.047852,0.014665,-0.208110,-0.208110,5.77,1848.0,NaN,NaN,86.0,182972.47,0.041266
4,ACCESORIES_1_005,ACCESORIES,45395.37,11912,3.810894,0.093071,0.0,0.079942,0.027095,0.421309,0.421309,3.96,1645.0,-0.090909,322.0,84.0,47171.52,-0.037653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3044,SUPERMARKET_3_823,SUPERMARKET,40432.09,12211,3.311120,0.104076,0.0,0.085526,0.031312,1.220504,1.220504,3.58,1785.0,-0.162011,-7.0,65.0,43715.38,-0.075106
3045,SUPERMARKET_3_824,SUPERMARKET,21651.76,7077,3.059455,0.105950,0.0,0.112739,0.017320,-0.802461,-0.802461,2.98,1869.0,-0.083969,924.0,46.0,21089.46,0.026663
3046,SUPERMARKET_3_825,SUPERMARKET,51628.55,10613,4.864652,0.070019,0.0,0.065913,0.015921,-0.013998,-0.013998,4.80,1841.0,-0.091255,217.0,19.0,50942.40,0.013469
3047,SUPERMARKET_3_826,SUPERMARKET,15437.48,10025,1.539898,0.199061,0.0,0.218041,0.046769,-0.073372,-0.073372,1.54,1092.0,-0.220779,364.0,133.0,15438.50,-0.000066
3048,SUPERMARKET_3_827,SUPERMARKET,10436.40,8697,1.200000,0.291480,0.0,0.200069,0.061899,0.729329,0.729329,1.20,770.0,NaN,NaN,93.0,10436.40,0.000000

In [ ]:
df_cluster.to_excel("/content/drive/MyDrive/MASTER EN DATA SCIENCE/Capstone/data_dsmarket/GrupoRetail_1/Proceso Total/BBDD output/bd_clustering.xlsx")

In [ ]:
# EL FICHERO bd_clustering SE MODIFICAR√Å A√ëADIENDO M√ÅS DATOS PASANDO A SER EL FICHERO bbdd_clustering_v1 QUE SE ENCUENTRA EN EL DIRECTORIO OUTPUT